### ISSUE TITLE
[morx] Failing test case MORX-8

### ISSUE THREAD

**Issue by brawer** [harfbuzz/harfbuzz#1190]
When using the current head of the HarfBuzz master branch (at 824111d4842b9a7bbbdcd147325f8f372ed3d37c) to run the [rendering engine test suite](https://github.com/unicode-org/text-rendering-tests), test case [MORX-8](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-8) is failing.

![image](https://user-images.githubusercontent.com/1527880/46136825-ba125e80-c248-11e8-91d7-d7d22bc4df52.png)

**Comment by behdad** [comment]
I haven't enabled morx in master yet, so all of them should fail. No?  When I enable it, up to MORX-28 pass.  Haven't tried newer ones.

**Comment by brawer** [comment]
When I apply the following patch to HarfBuzz, all MORX tests are passing with the exception of MORX-8; see the [test report](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html). Rebasing to today’s current master at 7e6e094abd27fd022fe9aea1872ef82f6a0cdcec makes no change.

```patch
diff --git a/src/hb-ot-shape.cc b/src/hb-ot-shape.cc
index 5404a5c3..c7d3e98d 100644
--- a/src/hb-ot-shape.cc
+++ b/src/hb-ot-shape.cc
@@ -632,7 +632,7 @@ hb_ot_substitute_complex (hb_ot_shape_context_t *c)
 
   c->plan->substitute (c->font, buffer);
 
-  if (0) /* XXX Call morx instead. */
+  if (1) /* XXX Call morx instead. */
     hb_aat_layout_substitute (c->font, c->buffer);
 }
```

I’m using https://github.com/unicode-org/text-rendering-tests#text-rendering-tests to run the test suite.

**Comment by behdad** [comment]
Weird.  It passes for me in the harfbuzz test suite itself.  I just updated from text-rendering-tests upstream and still passes.

**Comment by behdad** [comment]
Thanks for the Insertion tests.  They are great.  I'm looking into 32.

**Comment by behdad** [comment]
Also, there's a type copy/pasted many times in your test HTML: "fine-state".

**Comment by behdad** [comment]
Fixed MORX-32 BTW: https://github.com/harfbuzz/harfbuzz/commit/f4072e8cb81072cd6d51a2607efedb76c02e7db1

**Comment by behdad** [comment]
CFF-2 failure is curious.

**Comment by behdad** [comment]
I checked MORX-8 locally again.  Definitely works for me:
```
$ ../../../../util/hb-shape ../../../../../test/shaping/data/text-rendering-tests/fonts/TestMORXEight.ttf --verify --font-size=1000 --ned --remove-default-ignorables --font-funcs=ft --unicodes U+0031,U+0041,U+0042,U+0043
[one|B@914,0|C@1564,0|A@2196,0]
```

**Comment by behdad** [comment]
Still an issue?

**Comment by brawer** [comment]
Yes, still an issue: https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-8

Weird.

**Comment by behdad** [comment]
Can you try on the command-line with hb-shape?

**Comment by behdad** [comment]
> Can you try on the command-line with hb-shape?

@brawer

**Comment by brawer** [comment]
Weird, hb-shape gives the expected result, so it must be related to my test harness. But if something is off there, why only MORX-8?

The test failure can also be reproduced on Linux:

```sh
$ git clone --recursive https://github.com/unicode-org/text-rendering-tests.git
$ cd text-rendering-tests
$ python2.7 check.py --engine=FreeStack --output=reports/FreeStack.html
```

Here‘s a command to see the output from the failing test:

```sh
$ ./build/out/Default/fonttest --render=1ABC  --engine=FreeStack --font=fonts/TestMORXEight.ttf 
```

**Comment by ebraminio** [comment]
So lets assume it is out of harfbuzz scope for now but yet valuable thing to know the cause of course and lets close it till more information.

**Comment by behdad** [comment]
Humm. I'm debugging.  Let's keep open as reminder.  I mean, our issue tracker, unicode's, doesn't matter.

**Comment by behdad** [comment]
@khaledhosny can you test this through raqm?

**Comment by khaledhosny** [comment]
Looks like a bug in Raqm or the script detection algorithm. The digits at the start of the run are assigned Common script instead of Latin and thus ends up in a separate run. Adding a Latin character before the digit should workaround this. Not a HarfBuzz bug then.
