### ISSUE TITLE
Scaling change

### ISSUE THREAD

**Issue by forthy42** [harfbuzz/harfbuzz#3788]
Since my code suddenly didn't work anymore (x advances by factor 64 too small, unless there is kerning, then the kerning is same, but the non-kerning part a factor 64 too small) after installing Harfbuzz 5.x, I looked at the code, and found a number of places, where the advance getter was replaced by the _without_var_unscaled variant.

Please roll these changes back. You can't suddenly change scaling factors! In particular, you can't change scaling factors AND induce errors with kerning.

First screenshot showing how rendering works with the scaling that used to work up to 4.4.1:

![Screenshot_20220818_221835](https://user-images.githubusercontent.com/5509173/185487175-3bae6456-099f-4fe2-86b4-20824a57000a.png)

So now just multiply the horizontal scaling by 64, and see how the kerning goes wrong:

![Screenshot_20220818_221858](https://user-images.githubusercontent.com/5509173/185487201-a34f9dd7-10dc-4cf9-a495-29145af90711.png)

**Comment by khaledhosny** [comment]
Please specify the exact HarfBuzz version you are using.

**Comment by forthy42** [comment]
Screenshots made with 5.1.0.

**Comment by khaledhosny** [comment]
OK, we will need more details on how you are using HarfBuzz, and preferably some reproducible code.

**Comment by forthy42** [comment]
I'm using Harfbuzz from Gforth, and you can look here how to install the current snapshot (which works fine on harfbuzz 4.4.1):

https://gforth.org/

To get the rendering as described, you start

```
gforth minos2/tutorial/tutorial.fs markdown.fs
```

I use a harfbuzz buffer to get the positions with `hb_buffer_get_glyph_positions`. and then go through the array of returned items and use `x_advance` to compute the offset towards the next glyph.  I think this is a very straight forward way to use Harfbuzz and should be covered by your tests.

Just throw away the `_without_var_unscaled` changes, please.

**Comment by khaledhosny** [comment]
How are you creating the hb_font_t, how are you setting the size on them? are you using hb-ft? These are the important details. Please help us understand what the problem is, not what you *think* is the fix.

**Comment by behdad** [comment]
We don't intentionally break your code. So as Khaled says we need more information to fix the regression. Thanks.

**Comment by forthy42** [comment]
Fonts are created from freetype fonts via `hb_ft_font_create_referenced`, from fonts mostly created with `FT_New_Size` (several sizes for one single loaded font).

I tell you what change broke my code.  I think that's reasonable information.

And going from scaled to unscaled obviously must break code.

**Comment by behdad** [comment]
> (several sizes for one single loaded font).

This seems to be the root of the problem. It happened to work before by chance. Can you see if calling `hb_ft_font_changed()` every time you change the FT_Face font size helps?


> where the advance getter was replaced by the _without_var_unscaled variant.

That was just a rename of the existing function. Believe me, we didn't go from scaled to unscaled.

**Comment by behdad** [comment]
> > where the advance getter was replaced by the _without_var_unscaled variant.

The changes you are referring to are in `hb-ot-font`, which is irrelevant to `hb-ft`. You are using `hb-ft`. So I don't see how that's relevant.

**Comment by forthy42** [comment]
I don't change the FT_Font font size later after creation; I create references with new sizes, and from those the Harfbuzz fonts; those font references+harfbuzz font references are never changed, only the size is activated.  Adding `hb_ft_font_changed()` whenever I activate the corresponding size with `FT_Activate_Size()` doesn't change anything.  What I would expect if changes didn't propagate is that the x_advance matches a different size, not off by a factor of 64.

And please note that for glyph pairs with kerning, the kerning itself is still scaled as before, so when I adjust the Harfbuzz x_advance by the factor 64, I get this strange overlap of glyphs that should be moved a bit closer by kerning.

**Comment by behdad** [comment]
Any chance you can bisect harfbuzz to see which commit broke this? There were a few changes to hb-ft that regressed similarly but I thought we fixed those. Thanks in advance.

**Comment by forthy42** [comment]
I can try to bisect, but I have some additional information:

I use https://github.com/rougier/freetype-gl to cache the glyphs.  Freetype GL uses a non-uniform glyph transformation matrix with `FT_Set_Transform()`, which scales down horizontally by the factor 64, for reasons I don't know.  Taking that out (i.e. using a uniform transformation and setting the size accordingly) fixes rendering with 5.1.0; I'll check soon if this is a viable workaround, i.e. also works with 4.4.1.

**Comment by behdad** [comment]
Yes, that's what changed. We started using FT_Face's transform, mainly to be able to support bitmap fonts. But it has the side-effect you noticed. I'll see if I can revert that. Thanks for your patience.

**Comment by behdad** [comment]
@forthy42 Can you test if this PR fixes the issue for you:
https://github.com/harfbuzz/harfbuzz/pull/3791

**Comment by forthy42** [comment]
Yes, this PR fixes my issue. Build&install: still fails, /sbin/ldconfig to make the replacement libraries actually be found: fixed.

**Comment by behdad** [comment]
Thanks for checking!
